exports.statusCode = {
    otpCode: 555,
    ok: 200,
    unauth: 401,
    notFound: 404,
    validation: 400,
    failed: 1002,
    invalidURL: 1001,
    internalError: 1004,
    forbidden: 403,
    alreadyExist: 409,
    expiredOTP: 502,
    resedOTP: 503,
    internalServerError: 500,
}
exports.attendanceMsg = {
    file: 'Please select file',
    attendanceSuccess: 'File submitted successfully',
    invalidFormat: 'Only csv files are allowed',
    employeeIdReq: 'Employee id is required',
    dateReq: 'Please Select Date',
    codeReq: 'Employee code required',
    dataFetch: 'Data Fetch Successfully',
    attendanceId: 'AttendanceId required',
    empId: 'empId required',
    inTime: 'inTime required',
    outTime: 'outTime required',
}
exports.regularizedMsg = {
    regularizedIn: 'RegularizedIn require',
    regularizedOut: 'RegularizedOut require',
}
exports.employeeUpdateMsg = {
    permanentAddress: 'PermanentAddress is required',
    currentAddress: 'CurrentAddress is required',
    previousExperience: 'PreviousExperience is required',
    educationQualification: 'EducationQualification is required',
    familyDetails: 'FamilyDetails is required',
    document: 'Document is required',
    skills: 'Skills is required',
    technology: 'Technology is required',
    domain: 'Domain is required',
    nationality: 'Nationality Is Required',
}
exports.attendanceRegMsg = {
    regularizedIn: 'In time require',
    regularizedOut: 'Out time require',
    regularizedReason: 'Reason require',
    regularizedNote: 'Note require',
}
exports.timeLogMsg = {
    reportedDate: 'Please enter reported date',
    projectId: 'Please enter project id',
    billable: 'Please select billable type',
    companyId: 'Please enter company id',
    employeeId: 'Please enter employee id',
    taskReq: 'Please enter your tasks',
    totalHours: 'Please enter total hours',
    taskDetail: 'Please enter your detail',
    typeOfWork: 'Please enter typeOfWork',
    moduleName: 'Please enter duration',
    duration: 'Please enter moduleName',
    taskDetails: 'Please enter taskDetails',
}
exports.leaveApplyMsg = {
    name: 'Please enter name',
    appliedTo: 'Applied id is require',
    empId: 'Please enter empId',
    type: 'Please enter leave type',
    appliedTo: 'Please enter appliedTo',
    startDate: 'Please enter start date',
    endDate: 'Please enter end date',
    session: 'Please Select Session',
    reason: 'Please enter reason',
    appliedToHr: 'HR require',
}
exports.settings = {
    /** Pagination settings */
    count: 10,
    defaultPageNo: 1,
}
exports.holidayMsg = {
    name: 'Holiday name required',
    shift: 'Select shift',
    date: 'Date required',
    locations: 'Select locations',
    description: 'Description Required',
    holidayRequired: 'please select at least location & shift',
}
exports.shiftRotationValidation = {
    name: 'Shift rotation name in required',
    scheduleFrequency: 'Select schedule frequency for shift rotation',
    shiftRotation: 'Select rotation with shift wise',
    applicablePeriod: 'Select period for shift rotation',
    applicableFor: 'Select any to apply shift rotation',
}
exports.messages = {
    reportingManger: 'Please Select Reporting Manager',
    ProjectId: 'Please Enter Your Project Id',
    approvedToId: 'Please enter Approve To',
    AttendanceCsvFormat: 'Invalid format',
    notRegularize: 'Attendance not regularize',
    attendanceRegularized: 'There is no attendance for regularized',
    empId: 'Please Enter Your Employee Id',
    reqAccepted: 'Request Accepted',
    titleReq: 'Please enter title',
    assignReportingManager: "You don't have any reporting manager, please contact your Management team.",
    existReportingManager: 'Reporting Manager exist',
    empExist: 'User already exist with this email',
    invalidDocumentFormat: 'CSV format is required',
    notApprove: 'Leave not approved',
    alreadyApprove: (status) => `Leave already ${status}`,
    alreadyApproveAttendance: (status) => `Attendance  ${status}`,
    appliedTo: ' Please enter Applied to Id',
    status: 'Please Send Status',
    alreadyDeclined: 'Leave already Declined',
    otpReq: 'Please enter otp',
    mailSend: 'Mail send',
    notExist: 'User not exist',
    companyNot: 'Enter your company id',
    sizeExceeded: 'Please upload less then 5mb',
    pfdFile: 'Please upload your Pdf file',
    departments: 'Departments required',
    attendanceId: 'AttendanceId required',
    locations: 'Locations required',
    designations: 'Designations required',
    invalidFormat: 'Please Upload pdf file only',
    superAdmin: 'Please enter Super Admin credential',
    correctCorporateId: 'Please Check Corporate Id',
    invalidDocFormat: 'Only pdf,docx,doc file format are allowed.',
    isCompleted: 'completed',
    corporateId: 'Please Enter Corporate Id',
    invited: 'Please enter InvitedBy Id',
    systemNumber: 'Please enter number',
    // corporateReq: "Please enter corporate id",
    acceptedMailNotSend: 'Accepted Mail not send',
    confirmPswd: 'Password is Confirmed',
    declineInvitation: 'You can not login as you have declined invitation',
    accountNotActive: 'This Account is Not Active',
    declinedMailNotSend: 'Invite declined but email not sent',
    pswdChangeSuccess: 'Password changed successfully',
    tokenExist: 'Token has exist',
    addRegistered: 'Register Successfully',
    tokenReq: 'Token not Received',
    updateSuccess: 'Updated Successfully',
    isActive: 'Please specify status',
    proiderNotExist : "Provider not exists",
    deActivated: 'De-activated successfully',
    complete: 'Profile Completed',
    activated: 'Activated successfully',
    nameReq: 'Please Enter Your Company Name',
    emailReq: 'Please Enter Email',
    delSuccess: 'Delete Successfully',
    requiredFieldsMissing: 'Missing Required Field',
    exist: 'Already Exist',
    accountDeleted: 'Account Deleted',
    accountDecline: 'This account is decline by admin',
    passwordReq: 'Please Enter Password',
    invalidPassword: 'Please Enter Correct Password',
    incorrectEmail: 'Please Enter Correct Email',
    countryId: 'Please enter Country Id',
    addSuccess: 'Added Successfully',
    codeExist: 'Code already exist',
    idReq: 'Please enter Id',
    internalServerError: 'Internal Server Error',
    notallowed: 'You are not allowed to login.',
    ExecutedSuccessfully: 'Data Fetch Successfully',
    noRecordFound: 'No Record Found',
    loginSuccessfully: 'Login Successfully',
    branchId: 'Branch Id required',
    userNotFound: 'User Not Found',
    logoutSuccessfully: 'Logout Successfully',
    tokenExpire: 'Token has been expired',
    createdById: 'Created By Id required',
    companyId: 'Company Id required',
    sizeExceeded: 'Size should be less then 5mb',
    imgNotUpload: 'Image not uploaded',
    uploadSuccess: 'Uploaded successfully.',
    invalidImageFormat: 'Only jpeg,png file format are allowed.',
    invitation_fail: 'Invitation Failed :( Please try again later',
    imageDeleted: 'Image deleted',
    uploadTypeReq: 'Please specify upload type',
    image_upl: 'Please Upload Image',
    uploadSuccess: 'Uploaded Successfully',
    wrongEmail: 'Please Enter your Correct Email',
    forgotPasswordSuccess: 'Reset password link sent to your email',
    createPasswordSuccess: 'Password created successfully.',
    emailNotSend: 'Email  not sent',
    incorrectPassword: 'Incorrect Password',
    wrongOldPswd: 'Please Enter your Correct Old Password',
    cantSignupWithThisEmail: 'Sorry :( you cannot signup with this email. Please try with different email.',
    roleId: 'PLease Enter your Role Id',
    dataFound: 'Data not found',
    emailAlreadyExist: (isActive) => `Email already exists, ${isActive ? 'Please login' : ''}`,
    inviteLocationNotSpecify: 'Please select atLeast one location',
    inviteTypeNotSpecify: 'Please select atLeast one appointment type',
    providerLimitExceed: (providerLimit) => `You can not send invitation according to your plan your provider limit was ${providerLimit}`,
    empPolicy: 'Please Select Policy',
    resend: 'Resend Request Send Successfully',
    invalid_otp: 'Invalid OTP',
    declinedAttendance : "Declined Successfully",
    acceptedAttendance : "Accepted Successfully",
    alreadyApproved : "Already Approved",
    serverError : "Server Error"
}
exports.leaveMsg = {
    name: 'Please enter Name',
    code: 'Please enter code',
    appliedId: 'Please enter applied Id',
    color: 'Please Choose color',
    type: 'Please enter type',
    basedOn: 'Please select Based on leave',
    unit: 'Please select Unit',
    leaveId: 'Please Enter leave Id',
    gender: 'Please Select your Gender',
    maritalStatus: 'Please Select Marital Status',
    location: 'Please Select Choose Location',
    applicable: 'Please select All fields',
}
exports.roleName = {
    /** THERE SHOULD BE ONLY ONE ADMIN ROLE IN DATABASE */
    ADMIN: 'ADMIN',
    STAFF: 'STAFF',
    COMPANY: 'COMPANY',
    SUPERADMIN: 'SUPERADMIN',
    EMPLOYEE: 'EMPLOYEE',
}
exports.softwareMsg = {
    provider: 'Please Enter provider name',
    type: 'Please Enter type',
    purchasedOn: 'Please Enter purchase date',
    billingCycle: 'Please Enter number and unit',
    costAndCurrency: 'Please Enter cost & currency',
    // nextPaymentDate: "Please enter nextPaymentDate",
    userMail: 'Please Enter user mail',
    productId: 'Please Enter product id',
    url: 'Please Enter url',
    note: 'Please Enter note',
    password: 'Please enter password',
}
exports.projectMsg = {
    name: 'Please Enter name',
    description: 'Please Enter description',
    startDate: 'Please Enter startDate',
    endDate: 'Please Enter endDate',
    projectManager: 'Please Enter projectManager',
    projectLocation: 'Please Enter projectLocation',
    clientName: 'Please Enter clientName',
    corporateAddress: 'Please Enter corporateAddress',
    clientEmail: 'Please Enter clientEmail',
    clientPhoneNo: 'Please Enter clientPhoneNo',
    clientCode: 'Please enter clientCode',
    domainId: 'Please Select your Domain',
}
exports.teamMsg = {
    empId: 'Please enter employee id',
    cmpnyId: 'Please enter company id',
    projectId: 'Please enter project id',
    startDate: 'Please enter start date',
    endDate: 'Please enter end date',
    resourceAlready: 'Resource has been already allocated on this project',
}
exports.timeZone = {
    timeMsg: 'Timezone added successfully',
    code: 'code is required',
    timezoneId: 'Timezone id is required',
    alreadyExist: 'Code is already exist',
    name: 'Name is required',
}
exports.mailSubject = {
    paymentSuccess: 'Payment success',
    forgotPassword: 'Reset password link',
    invitationAccepted: 'Invitation accepted',
    invitationDeclined: 'Invitation declined',
    invitation: 'Invitation confirmation email',
    invitationConfirmation: 'Confirmation email',

    signUpSuccess: 'Sign-up success',
    withdraw: 'This Leave is WithDraw',
    // roleId: "PLease Enter your Role Id ",
}
exports.shiftMsg = {
    codeReq: 'Code require',
    name: 'Shift name Required',
    shift: 'Shift Required',
    color: 'Please enter color',
    sessions: 'Enter Sessions',
    timeZone: 'Please enter time zone',
    sessionsFirst: 'First sessions of in time is Required',
    sessionSecond: 'Second sessions of out time is required',
    calculateHours: 'Select any one to calculate shift hour based',
    fullDay: 'Enter full day hours',
    halfDay: 'Enter half day hours',
    days: 'Enter days',
}
exports.departmentMsg = {
    addDepartment: 'Department added Successfully',
    titleReq: 'Please enter title',
    depCode: 'Please Enter Department Code',
    departmentIdReq: 'Please enter DepartmentId',
    departmentCode: 'Department code already exist',
    departmentTitle: 'Department title already exist',
}
exports.roleMsg = {
    idReq: 'Please enter role id',
    notExist: 'There is no such role',
    nameReq: 'Please enter role name',
    titleReq: 'Please enter role title',
    addSuccess: 'Role added successfully',
    deleted: 'This role is deleted by Admin',
    notActive: 'This role is de-activated by admin',
    notSpecified: 'Please specify the role you want to assign',
    unableToGetAdminId: 'Internal server error !! Unable find admin id',
    unableToGetRole: 'Internal Error !! unable to get role. Please try again later',
    existButDeleted: (roleName) => `Please try to create new role by '${roleName}' name`,
    exist: (roleName, isActive) => `'${roleName}' role name already exist${isActive ? '' : ' but not active'}`,
}
exports.email = {
    userSignUpSubject: 'Registration confirmation email',
    invitationSubject: 'Invitation  confirmation email',
    forgotPasswordTitle: 'Forget password mail',
    invitationTitle: 'Invitation Email',
    notificationEmail: 'Notification Email',
    regularizedReq: 'An employee has requested to regularise time.',
    leaveApplyEmail: 'There is a Leave Request waiting for approval.',
    acceptanceSubject: 'Invitation acceptance confirmation.',
    shortFallAttendance: 'Short fall attendance',
    emailNotSend: 'You have successfully registered .But due to some reason confirmation email not sent on your registered email.Please contact our support staff or your account activated,you can login by using your email & password.',
    outOrInTimeEmail : "Warning!! You are not come or go office at right time."
}
exports.branchMsg = {
    addBranch: 'Branch Added Successfully',
    branchNameReq: 'Branch Name Required',
    branchCodeReq: 'Branch Code Required',
    addressReq: 'Address Required',
    phoneReq: 'Number Required',
    emailReq: 'Email Required',

    branch: 'branch Required',
    dateOfFoundationReq: 'Date Required',
}
exports.countryMsg = {
    titleReq: 'Please enter title',
}
exports.stateMsg = {
    titleReq: 'Please enter title',
    addState: 'State added Successfully',
    idReq: 'Please enter state id',
}
exports.designationMsg = {
    designationReq: 'Please enter Designation',
    addDesignation: 'Designation added Successfully',
    titleReq: 'Please enter title',
    designationCode: ' Please enter Designation Code',

    idReq: 'Please Enter Designation Id',
    existCode: 'Designation code already exist',
    alreadyAssociate: 'This code already associated with another designation in this department',
    alreadyExistTitle: 'This title already associated with another designation in this department',

    designationTitle: 'Designation title already exist',
    designationCodeExist: 'Designation code already exist',
}
exports.hardwareMsg = {
    systemNumber: 'Please Enter System Number ',
    typeOfSystem: 'Please Enter type Of System ',
    brand: 'Please Enter Brand Name',
    operatingSystem: 'Please Enter operating System ',
    processor: 'Please Enter processor ',
    generation: 'Please Enter Generation',
    processorGHZ: 'Please Enter processor GHZ',
    size: 'Please Enter Size ',
    numOfRam: 'Please Enter Number Of Ram',
    ssd: 'Please Enter SSD ',
    externalHardDisk: 'Please Enter external HardDisk ',
    cardName: 'Please enter Graphic Card name',
    cardSize: 'Please enter Graphic card size',
}
exports.policyMsg = {
    code: 'Please Enter Policy Code ',
    name: 'Please enter Name',
    file: 'Please Upload pdf File',
    description: 'Enter description',
    enforcePolicy: 'Please Select Enforce Policy',
    department: 'Please Enter Department',
    designation: 'Please Enter Designation',
    alreadyAccept: 'This Policy Already accepted',
}
exports.userMsg = {
    roleIdReq: 'Role Id Required',
    postalCodeReq: 'Postal Code is Required',
    cityReq: 'City is Required',
    stateReq: 'State is Required',
    countryReq: 'Country is Required',
    addressReq: 'Address is Required',
    firstNameReq: 'First name required',
    lastNameReq: 'Last name required',
    mobileReq: 'Number required',
    emailReq: 'Email required',
    passwordReq: 'Password required',
    addressReq: 'Address required',
    mobileNumberReq: 'Mobile No Required',
    postalCodeReq: 'Postal Code  Required',
    countryReq: 'Country Required',
    stateReq: 'State Required',
    cityReq: 'City Required',
    companyReq: 'City Required',

    imageReq: 'Image Required',

    //personNameReq: "Person name required",
}

exports.pdfType = 'application/pdf'
exports.pdffileType = 'file/pdf'
exports.docType = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
exports.oldDocType = 'application/msword'

exports.empMsg = {
    firstName: 'First name required',
    lastName: 'Last name required',
    middleName: 'Middle Name is required',
    fatherName: 'Father Name id required',
    email: 'Email required',
    salary: 'Please enter salary details',
    mobileNumber: 'Mobile No Required',
    age: ' Please enter your Age',
    dob: 'Please enter Your Date of birth',
    gender: 'Please Select your gender',
    empId: 'Please enter employee Id',
    spouse: 'Please enter your Spouse Name',
    postalCode: 'Please enter pin Code',
    designation: 'Please Enter  designation Id',
    department: 'Please Enter department Id',
    roleId: 'Please Enter roleId ',
    branchId: 'Please Enter branchId',
    dateOfJoining: 'Please Enter date Of Joining ',
    probationPeriod: 'Please Enter probation Period ',
    dateOfConfirmation: 'Please Enter date Of Confirmation ',
    status: 'Please Enter status ',
    empType: 'Please Enter employee Type ',
    shift: 'Please Enter Shift Id ',
    bankDetails: 'Please Enter Bank Details',
    account: 'PLease Enter Your bank Account Name',

    details: 'PLease Enter Your bank Account Details',

    number: 'Please Enter your bank Account Number',
    ifscCode: 'Please Enter your bank IFSC Code',
    branch: 'Please Enter your bank Branch',
    address: 'Please Enter Your Address',
    address1: 'Please Enter Your Address 1',
    city: 'Please select your City',
    resetKey: 'please enter reset key',
    bloodGroup: 'Please select your Blood Group',
    document: 'Please Upload your Document',
    country: 'Please select your Country',
    state: 'Please select your State ',
    docType: 'Please select your Document Type ',
    file: 'Please choose your File',
    number: ' Please enter Document Number',
    basic: 'Please enter basic',
    hra: 'Please enter hra',
    conveyance: 'Please enter conveyance',
    da: 'Please enter da',
    allowance: 'Please enter allowance',
    // reportingManager: 'Please enter reporting manager',
    monthlyCtc: 'Please enter monthlyCtc',
    annualCtc: 'Please enter annualCtc',
    effectiveDate: 'Please enter effectiveDate',
}

exports.roleMsg = {
    roleNameReq: 'Please enter role name',
    titleReq: 'Please enter role title',
    roleAdded: 'Added Successfully',
    roleUpdate: 'Updated Successfully',
}

exports.cryptoConfig = {
    cryptoAlgorithm: 'aes-256-ctr',
    cryptoPassword: 'd6F3Efeq',
    secret: 'zimo@!@#$%^@2021',
}

exports.directoryPath = {
    COMPANY: './uploads/company_logo/',
    USER: './uploads/profile/',
    EMPLOYEE: './uploads/employee_Image/',
    POLICY: './uploads/companyPolicy/',
    EMPLOYEE_DOCUMENT: './uploads/Employee_Document/',
    EMPLOYEE_CSV: './uploads/csv_Employee/',
    ATTENDANCE_CSV: './uploads/attendance/',

    ATTENDANCE_CSV1: 'uploads/attendance/',
    SUPER_ADMIN: './uploads/super_Admin/',
}

exports.domain = {
    titleReq: 'Please enter Title',
    descriptionReq: 'Please enter Description',
}

exports.technology = {
    titleReq: 'Please enter Title',
    descriptionReq: 'Please enter Description',
}

exports.skills = {
    titleReq: 'Please enter Title',
}
exports.company = {
    nameReq: 'Please Enter Your Company Name',
    // logoReq: "Please Upload your Image",
    headOfficeAdd: 'Please Enter Your Office Address',
    mobileNumber: 'Please enter your Mobile number',
    email: 'Please enter your Email',
    website: 'Please enter your Official site',
    dateOfFoundation: 'Please Enter your Foundation date',
    gst: 'Please Enter Your GST Number',
    esi: 'Please Enter Your ESI Number',
    pan: 'Please Enter Your PAN Number',
    tan: 'Please Enter Your TAN Number',
    // createdById: "Please Enter created By Id",
    // corporateId: "Please Enter Corporate Id",
}
exports.countryMsg = {
    titleReq: 'Please Upload your Image',
}

exports.imageType = ['image/png', 'image/jpeg']
exports.pdfType = 'application/pdf'
