module.exports = function (express) {
    const router = express.Router()

    require('./modules/domain/domain_routes')(router)
    require('./modules/technology/technology_routes')(router)
    require('./modules/skills/skills_routes')(router)
    require('./modules/designation/designation_routes')(router)
    require('./modules/role/role_routes')(router)
    require('./modules/user/user_routes')(router)
    require('./modules/department/department_routes')(router)
    require('./modules/country/country_routes')(router)
    require('./modules/state/state_routes')(router)
    require('./modules/company/company_routes')(router)
    require('./modules/branch/branch_routes')(router)
    require('./modules/shifts/shifts_routes')(router)
    require('./modules/software/software_routes')(router)
    require('./modules/timezone/timezone_routes')(router)
    require('./modules/hardware/hardware_routes')(router)
    require('./modules/leave/leave_routes')(router)
    require('./modules/holiday/holiday_routes')(router)
    require('./modules/company Policy/companyPolicy_routes')(router)
    require('./modules/shifts_rotation/shiftRotation_routes')(router)
    require('./modules/nationality/nationality_routes')(router)
    require('./modules/document/document_routes')(router)
    require('./modules/employee/emp_routes')(router)
    require('./modules/attendance/attendance_routes')(router)
    require('./modules/Project/Project_routes')(router)
    require('./modules/typeOfWork/typeOfWork_routes')(router)
    require('./modules/ProjectStatus/ProjectStatus_routes')(router)
    require('./modules/leaveApply/leaveApply_routes')(router)
    require('./modules/timelog/timelog_routes')(router)
    require('./modules/RolesAndPermissions/role_permission_routes')(router)

    return router
}
